export * from './user.resolver'
export * from './group.resolver'
export * from './groupList.resolver'
export * from './menu.resolver'
export * from './menuList.resolver'
export * from './province.resolver'
export * from './provinceList.resolver'
export * from './regency.resolver'
export * from './regencyList.resolver'
export * from './district.resolver'
export * from './districtList.resolver'
export * from './village.resolver'
export * from './villageList.resolver'
export * from './timeslot.resolver'
export * from './timeslotList.resolver'

export * from './adspot.resolver'
export * from './adspotList.resolver'
export * from './advertiser.resolver'
export * from './advertiserList.resolver'
export * from './advertiserPost.resolver'
export * from './advertiserPostList.resolver'

export * from './showPost.resolver'